### ISSUE TITLE
символ P

### ISSUE THREAD

**Issue by DakotaMitch** [Himura2la/DiggerSay#2]
кириллический символ Р ломает строку, превращая в нечитаемые символы. альтернативное решение - замена на латинский символ P 
![lgpuc-vmxtw](https://cloud.githubusercontent.com/assets/27846289/25265333/2d92eab2-2675-11e7-8119-5b15b78a1d32.jpg)

**Comment by Himura2la** [comment]
Хороший баг ) со скриншотом и понятным описанием. В идеале, еще бы ссылку привести

**Comment by Himura2la** [comment]
fixed
